import { BattleMoveAnimation, MoveContext, BattleFrame, EffectDrawContext } from "../types.js";
import { drawFlyEffect } from "../../../renderers/moves/gen1/move017_020.js";

export const flyMove: BattleMoveAnimation = {
  num: 19,
  key: "fly",
  nameKo: "공중날기",
  nameEn: "Fly",
  type: "flying",
  category: "physical",
  camera: { type: "sky", zoom: 1.35 },
  buildFrames: (ctx: MoveContext): BattleFrame[] => {
    const { isPlayer: isP, action: a, enemyHp, playerHp, textLineIdx } = ctx;
    const isCharging = Boolean(
      (a as any).isTurn1Launch ||
      (a as any).chargingMove === "fly" ||
      a.log?.includes("날아올랐다") ||
      a.log?.includes("flew up") ||
      (!a.wasDescentFromAir && (a.damage ?? 0) === 0 && !a.log?.includes("빗나갔다") && !a.log?.includes("missed") && !a.log?.includes("닿지 않았다"))
    );

    if (isCharging) {
      // 1턴: 도약 준비 웅크리기 -> 로켓처럼 수직 급상승 (세로로 얇아지며 순백색 섬광) -> 성층권 돌파 -> 화면 상공 밖으로 완전 소멸
      return [
        // 1. 도약 준비 웅크리기 (카메라 1.70배 타이트 줌인 밀착)
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: 8 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: 8 } : { x: 0, y: 0 },
          pScale: isP ? { x: 1.30, y: 0.75 } : undefined,
          eScale: !isP ? { x: 1.30, y: 0.75 } : undefined,
          cameraZoom: 1.70,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: false,
          eWhite: false,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-crouch",
          phaseName: "1. 도약 준비 (카메라 밀착)",
        },
        // 2. 수직 로켓 급상승 & 카메라 다이내믹 수직 추적 (성층권을 향해 카메라가 포켓몬을 따라 수직 상승!)
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -60 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -60 } : { x: 0, y: 0 },
          pScale: isP ? { x: 0.65, y: 1.45 } : undefined,
          eScale: !isP ? { x: 0.65, y: 1.45 } : undefined,
          cameraZoom: 1.60,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: isP,
          eWhite: !isP,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-launch-1",
          phaseName: "2. 수직 급상승 (발사)",
        },
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -140 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -140 } : { x: 0, y: 0 },
          pScale: isP ? { x: 0.45, y: 1.85 } : undefined,
          eScale: !isP ? { x: 0.45, y: 1.85 } : undefined,
          cameraZoom: 1.50,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: isP,
          eWhite: !isP,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-launch-2",
          phaseName: "2. 수직 급상승 (상공 가속)",
        },
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -240 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -240 } : { x: 0, y: 0 },
          pScale: isP ? { x: 0.35, y: 2.10 } : undefined,
          eScale: !isP ? { x: 0.35, y: 2.10 } : undefined,
          cameraZoom: 1.38,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: isP,
          eWhite: !isP,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-launch-3",
          phaseName: "2. 수직 급상승 (초고속 상승)",
        },
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -360 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -360 } : { x: 0, y: 0 },
          pScale: isP ? { x: 0.28, y: 2.30 } : undefined,
          eScale: !isP ? { x: 0.28, y: 2.30 } : undefined,
          cameraZoom: 1.25,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: isP,
          eWhite: !isP,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-launch-4",
          phaseName: "3. 상공 돌파 (성층권 진입)",
        },
        // 3. 성층권 관통 & 초고도 돌파
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -520 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -520 } : { x: 0, y: 0 },
          pScale: isP ? { x: 0.20, y: 2.50 } : undefined,
          eScale: !isP ? { x: 0.20, y: 2.50 } : undefined,
          cameraZoom: 1.10,
          cameraTrackAttacker: true,
          isAttackerPlayer: isP,
          pWhite: isP,
          eWhite: !isP,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-launch-5",
          phaseName: "3. 상공 돌파 (성층권 관통)",
        },
        // 4. 화면 밖 완전 퇴장 (전장 카메라 1.0 복귀 및 상공 은신 - UI 복귀 및 대사 표출)
        {
          delay: 66,
          pOffset: isP ? { x: 0, y: -9999 } : { x: 0, y: 0 },
          eOffset: !isP ? { x: 0, y: -9999 } : { x: 0, y: 0 },
          cameraZoom: 1.0,
          cameraTrackAttacker: false,
          hidePlayer: isP,
          hideEnemy: !isP,
          hidePShadow: isP,
          hideEShadow: !isP,
          hideUI: false,
          showEffect: false,
          hitFlash: false,
          enemyHp,
          playerHp,
          textLineIdx,
          moveEffect: a,
          phaseId: "fly-vanish",
          phaseName: "4. 상공 은신",
        }
      ];
    }

    // 2턴: 기존 활공 컷씬 -> 카메라 대각선 틸트 급강하 -> 전장 지면 돌입 및 크레이터 타격 작렬 -> 착지
    return [
      // 1. 성층권 직선 활공 3단계 (카메라 수평 트래킹 & 날갯짓 부유 전진)
      {
        delay: 66,
        diveStep: 1,
        skyCameraTilt: 0.0,
        pOffset: { x: -22, y: -10 },
        eOffset: { x: -22, y: -10 },
        pScale: isP ? { x: 1.05, y: 0.95 } : undefined,
        eScale: !isP ? { x: 1.05, y: 0.95 } : undefined,
        pRot: 0,
        eRot: 0,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-glide-1",
        phaseName: "1. 상공 활공 (진입)",
      },
      {
        delay: 66,
        diveStep: 2,
        skyCameraTilt: 0.0,
        pOffset: { x: 0, y: -14 },
        eOffset: { x: 0, y: -14 },
        pScale: isP ? { x: 1.08, y: 0.92 } : undefined,
        eScale: !isP ? { x: 1.08, y: 0.92 } : undefined,
        pRot: isP ? -0.02 : 0.02,
        eRot: !isP ? -0.02 : 0.02,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-glide-2",
        phaseName: "1. 상공 활공 (순항)",
      },
      {
        delay: 66,
        diveStep: 3,
        skyCameraTilt: 0.0,
        pOffset: { x: 22, y: -8 },
        eOffset: { x: 22, y: -8 },
        pScale: isP ? { x: 1.10, y: 0.90 } : undefined,
        eScale: !isP ? { x: 1.10, y: 0.90 } : undefined,
        pRot: isP ? 0.01 : -0.01,
        eRot: !isP ? 0.01 : -0.01,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-glide-3",
        phaseName: "1. 상공 활공 (가속)",
      },

      // 2. 다이내믹 카메라 대각선 틸트 뱅킹 & 급강하 3단계 (카메라 회전 틸트 + 유선형 세로 압축)
      {
        delay: 66,
        diveStep: 4,
        skyCameraTilt: isP ? 0.28 : -0.28,
        pOffset: { x: 12, y: 2 },
        eOffset: { x: 12, y: 2 },
        pScale: isP ? { x: 1.35, y: 0.70 } : undefined,
        eScale: !isP ? { x: 1.35, y: 0.70 } : undefined,
        pRot: isP ? 0.12 : -0.12,
        eRot: !isP ? 0.12 : -0.12,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-bank-1",
        phaseName: "2. 카메라 틸트 뱅킹 (선회)",
      },
      {
        delay: 66,
        diveStep: 5,
        skyCameraTilt: isP ? 0.54 : -0.54,
        pOffset: { x: 2, y: 16 },
        eOffset: { x: 2, y: 16 },
        pScale: isP ? { x: 1.65, y: 0.52 } : undefined,
        eScale: !isP ? { x: 1.65, y: 0.52 } : undefined,
        pRot: isP ? 0.24 : -0.24,
        eRot: !isP ? 0.24 : -0.24,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-bank-2",
        phaseName: "2. 카메라 틸트 뱅킹 (급강하 가속)",
      },
      {
        delay: 66,
        diveStep: 6,
        skyCameraTilt: isP ? 0.78 : -0.78,
        pOffset: { x: -8, y: 32 },
        eOffset: { x: -8, y: 32 },
        pScale: isP ? { x: 1.90, y: 0.38 } : undefined,
        eScale: !isP ? { x: 1.90, y: 0.38 } : undefined,
        pRot: isP ? 0.36 : -0.36,
        eRot: !isP ? 0.36 : -0.36,
        isHighSkyCutscene: true,
        hideUI: true,
        isAttackerPlayer: isP,
        showEffect: false,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-bank-3",
        phaseName: "2. 카메라 틸트 뱅킹 (지면 돌입)",
      },
      // 3. 전장 지면 돌입 & 적 포켓몬 크레이터 타격 작렬! (활공 컷씬 종료 ➔ 전장 복귀 & UI 복귀!)
      {
        delay: 100,
        pOffset: isP ? { x: 180, y: -60 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -180, y: 60 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.40, y: 0.65 } : undefined,
        eScale: !isP ? { x: 1.40, y: 0.65 } : undefined,
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: true,
        hitFlash: true,
        moveStep: 2,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-impact",
        phaseName: "3. 급강하 타격 작렬",
      },
      // 4. 타격 반동 후방 도약 & 부드러운 체공 활공 복귀
      {
        delay: 66,
        pOffset: isP ? { x: 135, y: -50 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -135, y: 50 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.15, y: 0.88 } : undefined,
        eScale: !isP ? { x: 1.15, y: 0.88 } : undefined,
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-rebound",
        phaseName: "4. 타격 반동 후방 도약",
      },
      {
        delay: 66,
        pOffset: isP ? { x: 80, y: -30 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -80, y: 30 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.05, y: 0.95 } : undefined,
        eScale: !isP ? { x: 1.05, y: 0.95 } : undefined,
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: false,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-return-glide",
        phaseName: "4. 공중 후방 활공",
      },
      {
        delay: 66,
        pOffset: isP ? { x: 30, y: -10 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -30, y: 10 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.02, y: 0.98 } : undefined,
        eScale: !isP ? { x: 1.02, y: 0.98 } : undefined,
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: false,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-return-descend",
        phaseName: "4. 발판 진입 하강",
      },
      {
        delay: 80,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: 0, y: 0 },
        pScale: isP ? { x: 1.08, y: 0.92 } : undefined,
        eScale: !isP ? { x: 1.08, y: 0.92 } : undefined,
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: false,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-landing-cushion",
        phaseName: "4. 발판 터치다운 안착",
      },
      {
        delay: 80,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: 0, y: 0 },
        isHighSkyCutscene: false,
        hideUI: false,
        showEffect: false,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        moveEffect: a,
        phaseId: "fly-landing",
        phaseName: "4. 전투 스탠스 복귀",
      }
    ];
  },
  drawEffect: (targetCtx: any, frame: BattleFrame, drawCtx: EffectDrawContext) => {
    if (frame.showEffect && drawCtx.targetPos) {
      drawFlyEffect(targetCtx, drawCtx.attackerPos || { x: 135, y: 285 }, drawCtx.targetPos, frame.moveStep ?? 4);
    }
  }
};
