import { BattleMoveAnimation, MoveContext, BattleFrame, EffectDrawContext } from "../types.js";
import { drawBindEffect } from "../../../renderers/moves/gen1/move017_020.js";

export const bindMove: BattleMoveAnimation = {
  num: 20,
  key: "bind",
  nameKo: "조이기",
  nameEn: "Bind",
  type: "normal",
  category: "physical",
  camera: { type: "target", zoom: 1.35 },
  buildFrames: (ctx: MoveContext): BattleFrame[] => {
    const { isPlayer: isP, isHit, isMiss, action: a, enemyHp, playerHp, textLineIdx } = ctx;
    const miss = isMiss || !isHit;

    return [
      // 1. Enter Left Foot (9 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 195, y: -62 } : (miss ? { x: 20, y: 4 } : { x: -8, y: 4 }),
        eOffset: !isP ? { x: -195, y: 114 } : (miss ? { x: 20, y: -4 } : { x: 8, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? -0.12 : undefined,
        eRot: !isP ? 0.12 : undefined,
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 1,
        phaseId: "bind-step-1",
        phaseName: "1. 하단 진입 (9시)",
      },
      // 2. Glide Front Bottom Foot (6 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 230, y: -54 } : (miss ? { x: 14, y: 3 } : { x: -5, y: 3 }),
        eOffset: !isP ? { x: -230, y: 118 } : (miss ? { x: 14, y: -3 } : { x: 5, y: -3 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? -0.06 : undefined,
        eRot: !isP ? 0.06 : undefined,
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 2,
        phaseId: "bind-step-2",
        phaseName: "2. 전면 글라이드 (6시)",
      },
      // 3. Curve Bottom-Right Ankle (4 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 272, y: -62 } : (miss ? { x: 18, y: 4 } : { x: -7, y: 4 }),
        eOffset: !isP ? { x: -272, y: 110 } : (miss ? { x: 18, y: -4 } : { x: 7, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? 0.06 : undefined,
        eRot: !isP ? -0.06 : undefined,
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 2,
        phaseId: "bind-step-3",
        phaseName: "3. 우측 커브 (4시)",
      },
      // 4. Ascend Right Flank Behind (3 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 290, y: -76 } : (miss ? { x: 20, y: 4 } : { x: -8, y: 4 }),
        eOffset: !isP ? { x: -290, y: 96 } : (miss ? { x: 20, y: -4 } : { x: 8, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? 0.12 : undefined,
        eRot: !isP ? -0.12 : undefined,
        drawEnemyOnTop: isP, // Completely behind defender
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 3,
        phaseId: "bind-step-4",
        phaseName: "4. 후면 상승 (3시)",
      },
      // 5. Wrap Waist Behind (12 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 260, y: -94 } : (miss ? { x: 22, y: 4 } : { x: -8, y: 4 }),
        eOffset: !isP ? { x: -260, y: 78 } : (miss ? { x: 22, y: -4 } : { x: 8, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? 0.08 : undefined,
        eRot: !isP ? -0.08 : undefined,
        drawEnemyOnTop: isP, // Behind defender
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 4,
        phaseId: "bind-step-5",
        phaseName: "5. 허리 감싸기 후면 (12시)",
      },
      // 6. Emerge Upper Left Chest (9 o'clock) (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 215, y: -102 } : (miss ? { x: 24, y: 4 } : { x: -9, y: 4 }),
        eOffset: !isP ? { x: -215, y: 70 } : (miss ? { x: 24, y: -4 } : { x: 9, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? -0.08 : undefined,
        eRot: !isP ? 0.08 : undefined,
        drawEnemyOnTop: !isP, // In front of upper chest
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 5,
        phaseId: "bind-step-6",
        phaseName: "6. 상체 전면 출현 (9시)",
      },
      // 7. Lock Upper Front Torso (60ms)
      {
        delay: 60,
        pOffset: isP ? { x: 235, y: -104 } : (miss ? { x: 25, y: 4 } : { x: -9, y: 4 }),
        eOffset: !isP ? { x: -235, y: 68 } : (miss ? { x: 25, y: -4 } : { x: 9, y: -4 }),
        pScale: isP ? { x: 0.74, y: 0.74 } : undefined,
        eScale: !isP ? { x: 1.36, y: 1.36 } : undefined,
        pRot: isP ? -0.04 : undefined,
        eRot: !isP ? 0.04 : undefined,
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp,
        playerHp,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 6,
        phaseId: "bind-step-7",
        phaseName: "7. 상체 전면 고정",
      },
      // 8. Full Constriction Squeeze Clamp & Impact Burst (160ms)
      {
        delay: 160,
        pOffset: isP ? { x: 245, y: -86 } : (miss ? { x: 26, y: 4 } : { x: -10, y: 4 }),
        eOffset: !isP ? { x: -245, y: 86 } : (miss ? { x: 26, y: -4 } : { x: 10, y: -4 }),
        pScale: isP ? { x: 0.76, y: 0.76 } : { x: 0.65, y: 1.40 },
        eScale: isP ? { x: 0.65, y: 1.40 } : { x: 1.40, y: 1.40 },
        pRot: 0,
        eRot: 0,
        drawEnemyOnTop: isP,
        showEffect: true,
        hitFlash: !miss,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 7, // Max Squeeze Clamp
        phaseId: "bind-step-8",
        phaseName: "8. 전신 압박 조이기 작렬",
      },
      // 9. Pulse Squeeze Lock (90ms)
      {
        delay: 90,
        pOffset: isP ? { x: 245, y: -86 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -245, y: 86 } : { x: 0, y: 0 },
        pScale: isP ? { x: 0.74, y: 0.74 } : { x: 0.80, y: 1.20 },
        eScale: isP ? { x: 0.80, y: 1.20 } : { x: 1.36, y: 1.36 },
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 8, // Pulse
        phaseId: "bind-step-9",
        phaseName: "9. 펄스 압박",
      },
      // 10. Smooth Spring Back Leap 1 (55ms)
      {
        delay: 55,
        pOffset: isP ? { x: 155, y: -65 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -155, y: 65 } : { x: 0, y: 0 },
        pScale: isP ? { x: 0.84, y: 0.84 } : { x: 0.92, y: 1.08 },
        eScale: isP ? { x: 0.92, y: 1.08 } : { x: 1.26, y: 1.26 },
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 9,
        phaseId: "bind-step-10",
        phaseName: "10. 반동 도약 1",
      },
      // 11. Smooth Spring Back Leap 2 (55ms)
      {
        delay: 55,
        pOffset: isP ? { x: 75, y: -32 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: -75, y: 32 } : { x: 0, y: 0 },
        pScale: isP ? { x: 0.92, y: 0.92 } : { x: 0.98, y: 1.02 },
        eScale: isP ? { x: 0.98, y: 1.02 } : { x: 1.12, y: 1.12 },
        drawEnemyOnTop: !isP,
        showEffect: true,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        moveStep: 9,
        phaseId: "bind-step-11",
        phaseName: "11. 반동 도약 2",
      },
      // 12. Touchdown Landing (60ms)
      {
        delay: 60,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: 0, y: 0 },
        pScale: undefined,
        eScale: undefined,
        pRot: undefined,
        eRot: undefined,
        drawEnemyOnTop: false,
        showEffect: false,
        hitFlash: false,
        enemyHp: a.enemyHpAfter,
        playerHp: a.playerHpAfter,
        textLineIdx,
        isBlur: false,
        moveEffect: a,
        phaseId: "recovery",
        phaseName: "12. 원위치 착지",
      }
    ];
  },
  drawEffect: (targetCtx: any, frame: BattleFrame, drawCtx: EffectDrawContext) => {
    if (frame.showEffect && drawCtx.targetPos) {
      drawBindEffect(targetCtx, drawCtx.targetPos, frame.moveStep ?? 2);
    }
  }
};
