// ============================================================================
// ⚠️ [개발/작업 지침 - AI 필독]
// 프레임별 이미지 추출 및 시각적 검증은 유저가 웹 뷰어(http://localhost:3456)에서
// 직접 확인하므로, 작업 시 에이전트가 매번 프레임을 일일이 추출/조회하지 말 것!
// ============================================================================

import { BattleMoveAnimation, MoveContext, BattleFrame } from "../types.js";
import {
  drawHyperBeamEffect,
  drawHyperBeamBehindEffect,
} from "../../../renderers/moves/gen1/move061_064.js";

/**
 * 063: 파괴광선 (Hyper Beam)
 *
 * 5세대 블랙/화이트 공식 배틀 연출 기반 파괴적 특수기:
 * 1. [초고출력 차징 & 전장 암전]:
 *    - 전장이 밤하늘처럼 짙게 어두워지며(dimAlpha: 0.85) 시전자 입가로 3중 응축 에너지 구체 형성
 * 2. [초거대 파괴광선 사출]:
 *    - 3단계 초거대 빔 코어 (순백 초고열 심선 + 붉은 주황 플라즈마 바디 + 퍼플/바이올렛 외곽 오라)
 *    - 광선 주위를 고속으로 나선 회전하는 에너지 링/스파이럴 쇄도
 * 3. [대상 직격 대격돌 & 다단 지진 진동]:
 *    - 피격 포켓몬 직격 시 전장 전체 순백/황금빛 섬광 작렬 & 극대 넉백 진동
 *    - 지면 균열 충격파 및 사방으로 비산하는 파괴 에너지 스파크
 * 4. [반동 턴 후유증]:
 *    - 막대한 에너지 방출 후 시전자가 지쳐 굳는 딜레이 연출
 */
export const hyperBeamMove: BattleMoveAnimation = {
  num: 63,
  key: "hyper-beam",
  nameKo: "파괴광선",
  nameEn: "Hyper Beam",
  type: "normal",
  category: "special",
  camera: { type: "target", zoom: 1.55, inlineGlideInFrames: 6 },
  drawBehindEffect: drawHyperBeamBehindEffect,
  drawEffect: drawHyperBeamEffect,
  buildFrames: (ctx: MoveContext): BattleFrame[] => {
    const { isPlayer: isP, isHit, action: a, enemyHp, playerHp, textLineIdx } = ctx;

    const baseFrame = {
      enemyHp,
      playerHp,
      textLineIdx,
      moveEffect: a,
      hitFlash: false,
    };

    return [
      // 1. [반투명 회색 구체 출현 & 암전]: 화면 절반 크기(140px)의 웅장한 회색 구체 형성 (60ms)
      {
        ...baseFrame,
        delay: 60,
        pOffset: isP ? { x: -2, y: 1 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 2, y: -1 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.03, y: 0.97 } : undefined,
        eScale: !isP ? { x: 1.03, y: 0.97 } : undefined,
        showEffect: true,
        moveStep: 1,
        dimAlpha: 0.45,
        chargeProgress: 0.15,
        greyRadius: 140,
        coreAlpha: 0.40,
        beamProgress: 0.0,
        phaseId: "hyper-charge-1",
        phaseName: "1. 반투명 회색 구체 출현 (140px, 60ms)",
      },
      // 2. [회색 구체 1차 수축]: 반경 112px로 완만히 수축 개시 (60ms)
      {
        ...baseFrame,
        delay: 60,
        pOffset: isP ? { x: -4, y: 2 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 4, y: -2 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.06, y: 0.94 } : undefined,
        eScale: !isP ? { x: 1.06, y: 0.94 } : undefined,
        showEffect: true,
        moveStep: 1,
        dimAlpha: 0.60,
        chargeProgress: 0.35,
        greyRadius: 112,
        coreAlpha: 0.52,
        beamProgress: 0.0,
        phaseId: "hyper-charge-2",
        phaseName: "2. 회색 구체 1차 수축 (112px, 60ms)",
      },
      // 3. [회색 구체 2차 수축]: 반경 86px로 가속 수축 (60ms)
      {
        ...baseFrame,
        delay: 60,
        pOffset: isP ? { x: -7, y: 3 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 7, y: -3 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.10, y: 0.90 } : undefined,
        eScale: !isP ? { x: 1.10, y: 0.90 } : undefined,
        showEffect: true,
        moveStep: 2,
        dimAlpha: 0.75,
        chargeProgress: 0.55,
        greyRadius: 86,
        coreAlpha: 0.65,
        beamProgress: 0.0,
        phaseId: "hyper-charge-3",
        phaseName: "3. 회색 구체 2차 수축 (86px, 60ms)",
      },
      // 4. [회색 구체 3차 수축]: 반경 64px로 중심 응축 (60ms)
      {
        ...baseFrame,
        delay: 60,
        pOffset: isP ? { x: -10, y: 5 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 10, y: -5 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.15, y: 0.85 } : undefined,
        eScale: !isP ? { x: 1.15, y: 0.85 } : undefined,
        showEffect: true,
        moveStep: 2,
        dimAlpha: 0.85,
        chargeProgress: 0.72,
        greyRadius: 64,
        coreAlpha: 0.78,
        beamProgress: 0.0,
        phaseId: "hyper-charge-4",
        phaseName: "4. 회색 구체 3차 수축 (64px, 60ms)",
      },
      // 5. [회색 구체 4차 수축]: 반경 46px로 발사점 직전 도달 (60ms)
      {
        ...baseFrame,
        delay: 60,
        pOffset: isP ? { x: -12, y: 6 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 12, y: -6 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.18, y: 0.82 } : undefined,
        eScale: !isP ? { x: 1.18, y: 0.82 } : undefined,
        showEffect: true,
        moveStep: 2,
        dimAlpha: 0.88,
        chargeProgress: 0.88,
        greyRadius: 46,
        coreAlpha: 0.90,
        beamProgress: 0.0,
        phaseId: "hyper-charge-5",
        phaseName: "5. 회색 구체 4차 수축 (46px, 60ms)",
      },
      // 6. [초기발사 원 수축 일치 & 극대 응축]: 회색 구체가 초기발사 원(32px)과 완벽 일치 (75ms)
      {
        ...baseFrame,
        delay: 75,
        pOffset: isP ? { x: -14, y: 7 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 14, y: -7 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.22, y: 0.80 } : undefined,
        eScale: !isP ? { x: 1.22, y: 0.80 } : undefined,
        showEffect: true,
        moveStep: 3,
        dimAlpha: 0.92,
        chargeProgress: 1.0,
        greyRadius: 32,
        coreAlpha: 1.0,
        beamProgress: 0.0,
        whiteFlashAlpha: 0.25,
        phaseId: "hyper-charge-max",
        phaseName: "6. 초기발사 원 수축 일치 & 극대 점화 (32px, 75ms)",
      },
      // 7. [초거대 파괴광선 즉시 발포 & 직격 대폭발]: 도달 과정 없이 즉시 100% 46px 빔 직격! (65ms)
      {
        ...baseFrame,
        delay: 65,
        pOffset: isP ? { x: -16, y: 4 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 16, y: -4 } : (isHit ? { x: 22, y: -8 } : { x: 0, y: 0 }),
        pScale: isP ? { x: 0.85, y: 1.18 } : undefined,
        eScale: !isP ? { x: 0.85, y: 1.18 } : undefined,
        hitFlash: isHit,
        showEffect: true,
        moveStep: 4,
        dimAlpha: 0.85,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 55,
        impactAlpha: 1.0,
        whiteFlashAlpha: isHit ? 0.70 : 0.0,
        phaseId: "hyper-beam-fire-instant",
        phaseName: "7. 초거대 파괴광선 즉시 발포 & 직격 (100% 46px, 65ms)",
      },
      // 8. [초거대 레이저 지속 방출 1 & 지진 진동 1]: 연속 폭발 & 셰이크 1 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -16, y: 4 } : (isHit ? { x: -20, y: 7 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 16, y: -4 } : (isHit ? { x: 20, y: -7 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 5,
        dimAlpha: 0.82,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 75,
        impactAlpha: 1.0,
        phaseId: "hyper-impact-1",
        phaseName: "8. 초거대 레이저 지속 방출 & 지진 진동 1 (70ms)",
      },
      // 9. [초거대 레이저 지속 방출 2 & 지진 진동 2]: 연속 폭발 & 셰이크 2 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -15, y: 3 } : (isHit ? { x: 18, y: -6 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 15, y: -3 } : (isHit ? { x: -18, y: 6 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 6,
        dimAlpha: 0.80,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 95,
        impactAlpha: 0.98,
        phaseId: "hyper-impact-2",
        phaseName: "9. 초거대 레이저 지속 방출 & 지진 진동 2 (70ms)",
      },
      // 10. [초거대 레이저 지속 방출 3 & 지진 진동 3]: 연속 폭발 & 셰이크 3 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -15, y: 4 } : (isHit ? { x: -16, y: 6 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 15, y: -4 } : (isHit ? { x: 16, y: -6 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 7,
        dimAlpha: 0.80,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 115,
        impactAlpha: 0.95,
        phaseId: "hyper-impact-3",
        phaseName: "10. 초거대 레이저 지속 방출 & 지진 진동 3 (70ms)",
      },
      // 11. [초거대 레이저 지속 방출 4 & 지진 진동 4]: 연속 폭발 & 셰이크 4 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -14, y: 3 } : (isHit ? { x: 15, y: -5 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 14, y: -3 } : (isHit ? { x: -15, y: 5 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 8,
        dimAlpha: 0.78,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 135,
        impactAlpha: 0.90,
        phaseId: "hyper-impact-4",
        phaseName: "11. 초거대 레이저 지속 방출 & 지진 진동 4 (70ms)",
      },
      // 12. [초거대 레이저 지속 방출 5 & 지진 진동 5]: 연속 폭발 & 셰이크 5 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -15, y: 4 } : (isHit ? { x: -14, y: 4 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 15, y: -4 } : (isHit ? { x: 14, y: -4 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 9,
        dimAlpha: 0.75,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 150,
        impactAlpha: 0.85,
        phaseId: "hyper-impact-5",
        phaseName: "12. 초거대 레이저 지속 방출 & 지진 진동 5 (70ms)",
      },
      // 13. [초거대 레이저 지속 방출 6 & 지진 진동 6]: 연속 폭발 & 셰이크 6 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -14, y: 3 } : (isHit ? { x: 12, y: -3 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 14, y: -3 } : (isHit ? { x: -12, y: 3 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 10,
        dimAlpha: 0.72,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 165,
        impactAlpha: 0.80,
        phaseId: "hyper-impact-6",
        phaseName: "13. 초거대 레이저 지속 방출 & 지진 진동 6 (70ms)",
      },
      // 14. [초거대 레이저 지속 방출 7 & 지진 진동 7]: 클라이맥스 폭발 & 셰이크 7 (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: isP ? { x: -15, y: 4 } : (isHit ? { x: -9, y: 2 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 15, y: -4 } : (isHit ? { x: 9, y: -2 } : { x: 0, y: 0 }),
        hitFlash: false,
        showEffect: true,
        moveStep: 11,
        dimAlpha: 0.70,
        beamProgress: 1.0,
        beamScale: 1.0,
        impactBurstR: 175,
        impactAlpha: 0.75,
        phaseId: "hyper-impact-7",
        phaseName: "14. 초거대 레이저 지속 방출 & 지진 진동 7 (70ms)",
      },
      // 15. [파괴광선 소멸 개시 & 충격파 확장 1]: 빔 감쇠 시작 (65ms)
      {
        ...baseFrame,
        delay: 65,
        pOffset: isP ? { x: -10, y: 3 } : (isHit ? { x: 5, y: -1 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 10, y: -3 } : (isHit ? { x: -5, y: 1 } : { x: 0, y: 0 }),
        showEffect: true,
        moveStep: 12,
        dimAlpha: 0.50,
        beamProgress: 1.0,
        beamFadeAlpha: 0.60,
        impactBurstR: 185,
        impactAlpha: 0.50,
        phaseId: "hyper-beam-dissipate-1",
        phaseName: "15. 파괴광선 소멸 개시 & 충격파 확장 1 (65ms)",
      },
      // 16. [파괴광선 소멸 개시 & 충격파 확장 2]: 빔 꼬리 잔상 소멸 (65ms)
      {
        ...baseFrame,
        delay: 65,
        pOffset: isP ? { x: -6, y: 2 } : (isHit ? { x: -2, y: 1 } : { x: 0, y: 0 }),
        eOffset: !isP ? { x: 6, y: -2 } : (isHit ? { x: 2, y: -1 } : { x: 0, y: 0 }),
        showEffect: true,
        moveStep: 12,
        dimAlpha: 0.30,
        beamProgress: 1.0,
        beamFadeAlpha: 0.25,
        impactBurstR: 195,
        impactAlpha: 0.30,
        phaseId: "hyper-beam-dissipate-2",
        phaseName: "16. 파괴광선 소멸 개시 & 충격파 확장 2 (65ms)",
      },
      // 17. [잔여 광선 완전 소멸]: (65ms)
      {
        ...baseFrame,
        delay: 65,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: 0, y: 0 },
        showEffect: true,
        moveStep: 13,
        dimAlpha: 0.15,
        beamProgress: 1.0,
        beamFadeAlpha: 0.0,
        impactBurstR: 200,
        impactAlpha: 0.10,
        phaseId: "hyper-beam-dissipate-3",
        phaseName: "17. 잔여 광선 완전 소멸 (65ms)",
      },
      // 18. [반동 턴 지연 1: 시전자 탈진 & 연기 잔향]: (85ms)
      {
        ...baseFrame,
        delay: 85,
        pOffset: isP ? { x: -4, y: 3 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 4, y: -3 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.08, y: 0.92 } : undefined,
        eScale: !isP ? { x: 1.08, y: 0.92 } : undefined,
        showEffect: true,
        moveStep: 14,
        dimAlpha: 0.10,
        beamFadeAlpha: 0.0,
        recoilSmokeAlpha: 0.85,
        phaseId: "hyper-recoil-delay-1",
        phaseName: "18. 반동 턴: 시전자 탈진 & 연기 1 (85ms)",
      },
      // 19. [반동 턴 지연 2: 시전자 탈진 & 연기 잔향]: (85ms)
      {
        ...baseFrame,
        delay: 85,
        pOffset: isP ? { x: -3, y: 2 } : { x: 0, y: 0 },
        eOffset: !isP ? { x: 3, y: -2 } : { x: 0, y: 0 },
        pScale: isP ? { x: 1.05, y: 0.95 } : undefined,
        eScale: !isP ? { x: 1.05, y: 0.95 } : undefined,
        showEffect: true,
        moveStep: 14,
        dimAlpha: 0.05,
        beamFadeAlpha: 0.0,
        recoilSmokeAlpha: 0.50,
        phaseId: "hyper-recoil-delay-2",
        phaseName: "19. 반동 턴: 시전자 탈진 & 연기 2 (85ms)",
      },
      // 20. [기술 종료 및 기본자세 회복]: (70ms)
      {
        ...baseFrame,
        delay: 70,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: 0, y: 0 },
        showEffect: false,
        moveStep: 15,
        dimAlpha: 0.0,
        phaseId: "hyper-end",
        phaseName: "20. 기술 종료 및 회복 (70ms)",
      },
    ];
  },
};