// ============================================================================
// ⚠️ [개발/작업 지침 - AI 필독]
// 프레임별 이미지 추출 및 시각적 검증은 유저가 웹 뷰어(http://localhost:3456)에서
// 직접 확인하므로, 작업 시 에이전트가 매번 프레임을 일일이 추출/조회하지 말 것!
// ============================================================================

import { BattleMoveAnimation, MoveContext, BattleFrame, EffectDrawContext } from "../types.js";
import { drawHazeEffect } from "../../../renderers/moves/gen1/move113_116.js";

/**
 * 114: 흑안개 (Haze) - 얼음 타입 변화기 (배틀 참가 전원의 능력치 랭크 변화 완전 초기화)
 *
 * 연출 구성:
 * #1. [카메라 줌아웃] 카메라 0.86x 와이드 뷰 글라이드아웃 & 반투명 암전 페이드인 & 흑안개 태동 (6프레임)
 * #2. [전역 순차 페이드인] 전장 전역 11개 거점의 가로 흑안개 구름이 각자의 시차를 두고 부드럽게 페이드인 (9프레임)
 * #3. [전장 완전 잠식] 11개 가스 구름이 전장 4사분면과 포켓몬 발밑/상공을 완전 포위하며 유기적 유동 (8프레임)
 * #4. [순차 승화 소멸] 가스 구름들이 순차적으로 엷어지며 승화 & 암전 자연스럽게 해제 (6프레임)
 * #5. [카메라 복귀] 0.86x 와이드 뷰에서 1.0x 중립 전장으로 부드럽게 복귀 (5프레임)
 */
export const hazeMove: BattleMoveAnimation = {
  num: 114,
  key: "haze",
  nameKo: "흑안개",
  nameEn: "Haze",
  type: "ice",
  category: "status",
  camera: { type: "custom" },
  drawEffect: (targetCtx: any, frame: BattleFrame, drawCtx: EffectDrawContext) => {
    if (!frame.showEffect && frame.moveStep === undefined) return;
    const { attackerPos, targetPos, pm, em, isPlayer } = drawCtx;
    const step = frame.moveStep ?? 1;
    const prog = frame.effectProgress ?? 0.5;
    const playerP = pm || (isPlayer ? attackerPos : targetPos);
    const enemyP = em || (isPlayer ? targetPos : attackerPos);
    drawHazeEffect(targetCtx, playerP, enemyP, step, prog, isPlayer);
  },
  buildFrames: (ctx: MoveContext): BattleFrame[] => {
    const { isPlayer: isP, action: a, enemyHp, playerHp, textLineIdx } = ctx;

    const baseFrame = {
      enemyHp,
      playerHp,
      textLineIdx,
      moveEffect: a,
      pRot: 0,
      eRot: 0,
      pOffset: { x: 0, y: 0 },
      eOffset: { x: 0, y: 0 },
      pScale: { x: 1.0, y: 1.0 },
      eScale: { x: 1.0, y: 1.0 },
      hitFlash: false,
      hideHud: false,
      hideUI: false,
    };

    const neutralCenter = { x: 280, y: 190 };
    const wideZoom = 0.86;

    return [
      // ======================================================================
      // Phase 1: 카메라 줌아웃 & 반투명 암전 페이드인 & 가로 흑안개 태동 (6프레임)
      // ======================================================================
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.970,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.03,
        phaseId: "haze-zoomout-1",
        phaseName: "#1. 줌아웃 & 흑안개 태동 (1/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.940,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.07,
        phaseId: "haze-zoomout-2",
        phaseName: "#1. 줌아웃 & 흑안개 태동 (2/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.910,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.11,
        phaseId: "haze-zoomout-3",
        phaseName: "#1. 줌아웃 & 흑안개 태동 (3/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.885,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.15,
        phaseId: "haze-zoomout-4",
        phaseName: "#1. 줌아웃 & 흑안개 태동 (4/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.870,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.19,
        phaseId: "haze-zoomout-5",
        phaseName: "#1. 줌아웃 & 흑안개 태동 (5/6)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 1,
        effectProgress: 0.23,
        phaseId: "haze-zoomout-6",
        phaseName: "#1. 와이드 샷 안착 (6/6)",
      },

      // ======================================================================
      // Phase 2: 전장 전역 가로 흑안개 구름 순차 페이드인 확산 (9프레임)
      // ======================================================================
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.27,
        phaseId: "haze-expansion-1",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (1/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.31,
        phaseId: "haze-expansion-2",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (2/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.35,
        phaseId: "haze-expansion-3",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (3/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.39,
        phaseId: "haze-expansion-4",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (4/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.43,
        phaseId: "haze-expansion-5",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (5/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.47,
        phaseId: "haze-expansion-6",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (6/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.51,
        phaseId: "haze-expansion-7",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (7/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.55,
        phaseId: "haze-expansion-8",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (8/9)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 2,
        effectProgress: 0.59,
        phaseId: "haze-expansion-9",
        phaseName: "#2. 전장 전역 흑안개 순차 페이드인 (9/9)",
      },

      // ======================================================================
      // Phase 3: 전장 완전 잠식 & 묵직한 반투명 암전 & 부드러운 유동 (8프레임)
      // ======================================================================
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.63,
        phaseId: "haze-engulf-1",
        phaseName: "#3. 전장 전역 흑안개 완전 잠식 (1/8)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.66,
        phaseId: "haze-engulf-2",
        phaseName: "#3. 전장 전역 흑안개 완전 잠식 (2/8)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.69,
        phaseId: "haze-engulf-3",
        phaseName: "#3. 전장 전역 흑안개 완전 잠식 (3/8)",
      },
      {
        ...baseFrame,
        delay: 48,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.72,
        phaseId: "haze-engulf-4",
        phaseName: "#3. 묵직한 반투명 암전 & 흑안개 포위 (4/8)",
      },
      {
        ...baseFrame,
        delay: 48,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.75,
        phaseId: "haze-engulf-5",
        phaseName: "#3. 묵직한 반투명 암전 & 흑안개 포위 (5/8)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.78,
        phaseId: "haze-engulf-6",
        phaseName: "#3. 흑안개 가스 매끄러운 유동 (6/8)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.81,
        phaseId: "haze-engulf-7",
        phaseName: "#3. 흑안개 가스 매끄러운 유동 (7/8)",
      },
      {
        ...baseFrame,
        delay: 45,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 3,
        effectProgress: 0.84,
        phaseId: "haze-engulf-8",
        phaseName: "#3. 흑안개 가스 잠식 정점 (8/8)",
      },

      // ======================================================================
      // Phase 4: 구름 순차 승화 & 암전 페이드아웃 (6프레임)
      // ======================================================================
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 0.87,
        phaseId: "haze-dissipate-1",
        phaseName: "#4. 흑안개 순차 승화 페이드아웃 (1/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 0.90,
        phaseId: "haze-dissipate-2",
        phaseName: "#4. 흑안개 순차 승화 페이드아웃 (2/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 0.93,
        phaseId: "haze-dissipate-3",
        phaseName: "#4. 흑안개 순차 승화 페이드아웃 (3/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 0.96,
        phaseId: "haze-dissipate-4",
        phaseName: "#4. 잔여 가스 스트림 분산 (4/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 0.98,
        phaseId: "haze-dissipate-5",
        phaseName: "#4. 암전 해제 & 잔여 안개 소멸 (5/6)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: wideZoom,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 4,
        effectProgress: 1.00,
        phaseId: "haze-dissipate-6",
        phaseName: "#4. 흑안개 완전 소멸 (6/6)",
      },

      // ======================================================================
      // Phase 5: 카메라 부드러운 중립 복귀 (5프레임)
      // ======================================================================
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.895,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 5,
        effectProgress: 1.00,
        phaseId: "haze-return-1",
        phaseName: "#5. 카메라 중립 복귀 (1/5)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.930,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 5,
        effectProgress: 1.00,
        phaseId: "haze-return-2",
        phaseName: "#5. 카메라 중립 복귀 (2/5)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.965,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 5,
        effectProgress: 1.00,
        phaseId: "haze-return-3",
        phaseName: "#5. 카메라 중립 복귀 (3/5)",
      },
      {
        ...baseFrame,
        delay: 42,
        cameraZoom: 0.990,
        cameraFocal: neutralCenter,
        _gen5Camera: true,
        showEffect: true,
        moveStep: 5,
        effectProgress: 1.00,
        phaseId: "haze-return-4",
        phaseName: "#5. 카메라 중립 복귀 (4/5)",
      },
      {
        ...baseFrame,
        delay: 60,
        cameraZoom: 1.0,
        cameraFocal: null,
        _gen5Camera: false,
        showEffect: false,
        moveStep: 5,
        effectProgress: 1.00,
        afterCameraReturn: true,
        phaseId: "haze-return-5",
        phaseName: "#5. 맑은 전장 복귀 완료 (5/5)",
      },
    ];
  },
};
