// ============================================================================
// ⚠️ [개발/작업 지침 - AI 필독]
// 프레임별 이미지 추출 및 시각적 검증은 유저가 웹 뷰어(http://localhost:3456)에서
// 직접 확인하므로, 작업 시 에이전트가 매번 프레임을 일일이 추출/조회하지 말 것!
// ============================================================================

import { BattleMoveAnimation, MoveContext, BattleFrame, EffectDrawContext } from "../types.js";
import { drawSelfDestructEffect, drawSelfDestructBehindEffect } from "../../../renderers/moves/gen1/move117_120.js";

/**
 * 120: 자폭 (Self-Destruct) - 노말 타입 물리 기술 (위력 200)
 *
 * 연출 구성 (유저 피드백 100% 반영: 크리퍼식 순백 깜빡임 & 펑!):
 * 1. [플레이어 시전 시]:
 *    - 상대를 향해 걸어가기 (#1 ~ #5) ➔ 중간 지점 도착 및 멈춤 (#6 ~ #7)
 *    - 3D 회전 전환 (#8 ~ #10) ➔ 트레이너/카메라를 정면(usePlayerFront)으로 응시 (#11 ~ #13, 정적/코믹 비트)
 *    - 다시 상대를 향해 3D 회전 (#14 ~ #16) ➔ 전투 자세 정렬 (#17)
 *    - 상대 코앞 다가가기 (#18 ~ #20)
 *    - [크리퍼 점멸 틱]: 이펙트 없이 신체가 부풀어오르며 순백 깜빡임 가속 (#21 ~ #26) ➔ 기폭 직전 극대 팽창 순백 고정 (#27)
 *    - 펑! 기폭 (시전자 즉시 산화 소멸, HP: 0) & 2중 초음속 충격파 & 거대 9-로브 화구 (#28 ~ #32)
 * 2. [상대(Enemy) 시전 시 - 유저 요청: 뒤돌아보지 않고 직진]:
 *    - 플레이어를 향해 곧장 걸어가기 (#1 ~ #6) ➔ 플레이어 코앞 도착 (#7)
 *    - [크리퍼 점멸 틱]: 신체가 부풀어오르며 순백 깜빡임 가속 (#8 ~ #13) ➔ 기폭 직전 극대 팽창 순백 고정 (#14)
 *    - 펑! 기폭 (상대 즉시 소멸, enemyHp: 0) & 거대 대폭발 & 플레이어 최대 넉백 및 피해 (#15 ~ #19)
 */
export const selfDestructMove: BattleMoveAnimation = {
  num: 120,
  key: "self-destruct",
  nameKo: "자폭",
  nameEn: "Self-Destruct",
  type: "normal",
  category: "physical",
  camera: { type: "target", zoom: 1.45, delayUntilStep: 3 },
  drawBehindEffect: (targetCtx: any, frame: BattleFrame, drawCtx: EffectDrawContext) => {
    if (!frame.showEffect) return;
    const { targetPos, isPlayer: isP } = drawCtx;
    const blastX = targetPos.x - (isP ? 25 : -25);
    const blastY = targetPos.y + 12;
    drawSelfDestructBehindEffect(targetCtx, { x: blastX, y: blastY }, frame.moveStep ?? 1, frame.effectProgress ?? 0.5);
  },
  drawEffect: (targetCtx: any, frame: BattleFrame, drawCtx: EffectDrawContext) => {
    if (!frame.showEffect) return;
    const { attackerPos, targetPos, isPlayer: isP } = drawCtx;
    const curCasterX = isP ? (attackerPos.x + (frame.pOffset?.x ?? 0)) : (attackerPos.x + (frame.eOffset?.x ?? 0));
    const curCasterY = isP ? (attackerPos.y + (frame.pOffset?.y ?? 0)) : (attackerPos.y + (frame.eOffset?.y ?? 0));
    const blastX = targetPos.x - (isP ? 25 : -25);
    const blastY = targetPos.y + 12;
    drawSelfDestructEffect(targetCtx, { x: curCasterX, y: curCasterY }, { x: blastX, y: blastY }, frame.moveStep ?? 1, frame.effectProgress ?? 0.5, isP);
  },
  buildFrames: (ctx: MoveContext): BattleFrame[] => {
    const { isPlayer: isP, isHit, action: a, enemyHp, playerHp, textLineIdx } = ctx;

    const baseFrame = {
      enemyHp,
      playerHp,
      textLineIdx,
      moveEffect: a,
      pRot: 0,
      eRot: 0,
    };

    // =========================================================================
    // 1. 플레이어 시전: 걸어가기 ➔ 중간 멈춤 ➔ 트레이너 돌아보기 ➔ 돌아서서 코앞 쇄도 ➔ 크리퍼 점멸 ➔ 펑!
    // =========================================================================
    if (isP) {
      return [
        // #1. 걸어가기 (1)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 20, y: -9 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.04,
          phaseId: "selfdestruct-walk1",
          phaseName: "#1. 걸어가기 (1)",
        },
        // #2. 걸어가기 (2)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 40, y: -21 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.08,
          phaseId: "selfdestruct-walk2",
          phaseName: "#2. 걸어가기 (2)",
        },
        // #3. 걸어가기 (3)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 60, y: -28 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.12,
          phaseId: "selfdestruct-walk3",
          phaseName: "#3. 걸어가기 (3)",
        },
        // #4. 걸어가기 (4)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 80, y: -40 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.16,
          phaseId: "selfdestruct-walk4",
          phaseName: "#4. 걸어가기 (4)",
        },
        // #5. 걸어가기 (5)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 98, y: -46 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.20,
          phaseId: "selfdestruct-walk5",
          phaseName: "#5. 걸어가기 (5)",
        },
        // #6. 중간 지점 도착
        {
          ...baseFrame,
          delay: 140,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.24,
          phaseId: "selfdestruct-walk-arrive",
          phaseName: "#6. 중간 지점 도착",
        },
        // #7. 멈춤 (정지)
        {
          ...baseFrame,
          delay: 180,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.28,
          phaseId: "selfdestruct-pause",
          phaseName: "#7. 멈춤 (정지)",
        },
        // #8. 뒤돌아서기 시작 (3D 수평 압축)
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.50, y: 1.0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.32,
          phaseId: "selfdestruct-turn-start",
          phaseName: "#8. 뒤돌아서기 시작 (회전)",
        },
        // #9. 회전 90도 (측면 얇아짐)
        {
          ...baseFrame,
          delay: 100,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.15, y: 1.04 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.35,
          phaseId: "selfdestruct-turn-mid",
          phaseName: "#9. 회전 90도 (측면)",
        },
        // #10. 전면 모습 전환
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.65, y: 1.0 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.38,
          phaseId: "selfdestruct-turn-front",
          phaseName: "#10. 전면 모습 전환",
        },
        // #11. 트레이너 바라보기 (앞모습 1)
        {
          ...baseFrame,
          delay: 240,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.0, y: 1.0 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.40,
          phaseId: "selfdestruct-lookback1",
          phaseName: "#11. 트레이너 바라보기 (앞모습 1)",
        },
        // #12. 트레이너 바라보기 (앞모습 2 - 정적/코믹 비트)
        {
          ...baseFrame,
          delay: 260,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.0, y: 1.0 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.42,
          phaseId: "selfdestruct-lookback2",
          phaseName: "#12. 트레이너 바라보기 (앞모습 2)",
        },
        // #13. 트레이너 바라보기 (앞모습 3)
        {
          ...baseFrame,
          delay: 220,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.0, y: 1.0 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.44,
          phaseId: "selfdestruct-lookback3",
          phaseName: "#13. 트레이너 바라보기 (앞모습 3)",
        },
        // #14. 다시 돌아서기 시작
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.50, y: 1.0 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.46,
          phaseId: "selfdestruct-turnback-start",
          phaseName: "#14. 다시 돌아서기 시작",
        },
        // #15. 회전 90도 (측면)
        {
          ...baseFrame,
          delay: 100,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.15, y: 1.04 },
          usePlayerFront: true,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.48,
          phaseId: "selfdestruct-turnback-mid",
          phaseName: "#15. 회전 90도 (측면)",
        },
        // #16. 후면 모습 전환
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 0.65, y: 1.0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.49,
          phaseId: "selfdestruct-turnback-rear",
          phaseName: "#16. 후면 모습 전환",
        },
        // #17. 적을 향해 다시 서기
        {
          ...baseFrame,
          delay: 160,
          pOffset: { x: 115, y: -54 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.0, y: 1.0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 1,
          effectProgress: 0.50,
          phaseId: "selfdestruct-face-target",
          phaseName: "#17. 적을 향해 다시 서기",
        },

        // =====================================================================
        // STEP 2: 상대 코앞 다가가기 & 크리퍼식 순백 깜빡임 (Creeper Ticking)
        // =====================================================================
        // #18. 다가가기 (1)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 140, y: -65 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.51,
          phaseId: "selfdestruct-approach1",
          phaseName: "#18. 다가가기 (1)",
        },
        // #19. 다가가기 (2)
        {
          ...baseFrame,
          delay: 130,
          pOffset: { x: 165, y: -76 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.53,
          phaseId: "selfdestruct-approach2",
          phaseName: "#19. 다가가기 (2)",
        },
        // #20. 상대 코앞 도착
        {
          ...baseFrame,
          delay: 140,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.55,
          phaseId: "selfdestruct-reach",
          phaseName: "#20. 상대 코앞 도착",
        },
        // #21. 크리퍼 점멸 틱 1 (1차 팽창 & 순백 플래시)
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.03, y: 1.03 },
          casterWhite: true,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.58,
          phaseId: "selfdestruct-tick1",
          phaseName: "#21. 크리퍼 점멸 1 (순백)",
        },
        // #22. 크리퍼 점멸 틱 1-off (원색 복귀 & 미세 팽창)
        {
          ...baseFrame,
          delay: 110,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.05, y: 1.05 },
          casterWhite: false,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.60,
          phaseId: "selfdestruct-tick1-off",
          phaseName: "#22. 팽창 대기 1",
        },
        // #23. 크리퍼 점멸 틱 2 (2차 팽창 & 순백 플래시)
        {
          ...baseFrame,
          delay: 100,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.08, y: 1.08 },
          casterWhite: true,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.62,
          phaseId: "selfdestruct-tick2",
          phaseName: "#23. 크리퍼 점멸 2 (순백)",
        },
        // #24. 크리퍼 점멸 틱 2-off (원색 복귀 & 추가 팽창)
        {
          ...baseFrame,
          delay: 90,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.10, y: 1.10 },
          casterWhite: false,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.64,
          phaseId: "selfdestruct-tick2-off",
          phaseName: "#24. 팽창 대기 2",
        },
        // #25. 크리퍼 점멸 틱 3 (고속 팽창 & 순백 플래시)
        {
          ...baseFrame,
          delay: 90,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.12, y: 1.12 },
          casterWhite: true,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.66,
          phaseId: "selfdestruct-tick3",
          phaseName: "#25. 크리퍼 점멸 3 (순백)",
        },
        // #26. 크리퍼 점멸 틱 3-off (원색 복귀 & 임계 직전)
        {
          ...baseFrame,
          delay: 80,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.14, y: 1.14 },
          casterWhite: false,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.68,
          phaseId: "selfdestruct-tick3-off",
          phaseName: "#26. 팽창 대기 3",
        },
        // #27. 기폭 직전 팽창 (순백 고정 - 크리퍼 기폭 임계!)
        {
          ...baseFrame,
          delay: 140,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          pScale: { x: 1.16, y: 1.16 },
          casterWhite: true,
          usePlayerFront: false,
          showEffect: false,
          hitFlash: false,
          moveStep: 2,
          effectProgress: 0.70,
          phaseId: "selfdestruct-critical-white",
          phaseName: "#27. 기폭 직전 팽창 (순백 고정)",
        },

        // =====================================================================
        // STEP 3: 펑! (초대형 대폭발 & 시전자 자폭 소멸)
        // =====================================================================
        // #28. 펑! 기폭 (시전자 산화 소멸 & 백색 섬광 & 최대 셰이크 & 피크 블러)
        {
          ...baseFrame,
          delay: 150,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          cameraPan: { x: -10, y: 7 },
          cameraBlur: 4.5,
          hidePlayer: true,
          showEffect: true,
          hitFlash: true,
          moveStep: 3,
          effectProgress: 0.72,
          phaseId: "selfdestruct-detonate",
          phaseName: "#28. 펑! 기폭 (시전자 소멸 & 섬광)",
        },
        // #29. 초음속 충격파 분출 (폭풍 반동 셰이크 & 강한 블러)
        {
          ...baseFrame,
          delay: 150,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 22, y: -8 },
          cameraPan: { x: 9, y: -7 },
          cameraBlur: 3.8,
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 0.76,
          phaseId: "selfdestruct-shockwave-burst",
          phaseName: "#29. 충격파 확산 (반동 셰이크 & 블러)",
        },
        // #30. 화구 팽창 & 1차 여진 (강한 셰이크 & 중간 블러 유지)
        {
          ...baseFrame,
          delay: 160,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 38, y: -15 },
          cameraPan: { x: -7, y: 5 },
          cameraBlur: 2.8,
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 0.81,
          phaseId: "selfdestruct-fireball-expand",
          phaseName: "#30. 화구 팽창 (여진 셰이크 & 블러 유지)",
        },
        // #31. 거대 화구 절정 & 최대 넉백 (중간 셰이크 & 블러 완화)
        {
          ...baseFrame,
          delay: 180,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 48, y: -20 },
          cameraPan: { x: 5, y: -4 },
          cameraBlur: 1.8,
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 0.87,
          phaseId: "selfdestruct-mushroom-apex",
          phaseName: "#31. 거대 화구 절정 & 최대 넉백",
        },
        // #32. 흑연 연막 확산 & 파편 비산 (소강 셰이크 & 미세 블러)
        {
          ...baseFrame,
          delay: 180,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 30, y: -12 },
          cameraPan: { x: -3, y: 2 },
          cameraBlur: 0.8,
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 0.93,
          phaseId: "selfdestruct-smoke-billow",
          phaseName: "#32. 흑연 연막 확산 (소강 셰이크)",
        },
        // #33. 폭발 잔흔 & 연기 소멸 (미세 잔진 & 선명 복귀)
        {
          ...baseFrame,
          delay: 180,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 14, y: -5 },
          cameraPan: { x: 1, y: -1 },
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 0.98,
          phaseId: "selfdestruct-dissipate",
          phaseName: "#33. 폭발 잔흔 & 연기 소멸",
        },
        // #34. 완전 안정화 & 정렬 (카메라 원위치 복귀)
        {
          ...baseFrame,
          delay: 190,
          pOffset: { x: 185, y: -86 },
          eOffset: { x: 0, y: 0 },
          cameraPan: { x: 0, y: 0 },
          hidePlayer: true,
          showEffect: true,
          hitFlash: false,
          moveStep: 3,
          effectProgress: 1.0,
          phaseId: "selfdestruct-settle",
          phaseName: "#34. 완전 안정화 (원위치 복귀)",
        },
      ];
    }

    // =========================================================================
    // 2. 상대(Enemy) 시전: 뒤돌아보지 않고 곧장 플레이어 코앞으로 직진 ➔ 크리퍼 점멸 ➔ 펑!
    // =========================================================================
    return [
      // #1. 플레이어에게 걸어가기 (1)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -25, y: 11 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.08,
        phaseId: "selfdestruct-enemy-walk1",
        phaseName: "#1. 다가가기 (1)",
      },
      // #2. 플레이어에게 걸어가기 (2)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -52, y: 24 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.16,
        phaseId: "selfdestruct-enemy-walk2",
        phaseName: "#2. 다가가기 (2)",
      },
      // #3. 플레이어에게 걸어가기 (3)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -80, y: 37 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.24,
        phaseId: "selfdestruct-enemy-walk3",
        phaseName: "#3. 다가가기 (3)",
      },
      // #4. 플레이어에게 걸어가기 (4)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -108, y: 50 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.32,
        phaseId: "selfdestruct-enemy-walk4",
        phaseName: "#4. 다가가기 (4)",
      },
      // #5. 플레이어에게 걸어가기 (5)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -136, y: 63 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.40,
        phaseId: "selfdestruct-enemy-walk5",
        phaseName: "#5. 다가가기 (5)",
      },
      // #6. 플레이어에게 걸어가기 (6)
      {
        ...baseFrame,
        delay: 130,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -164, y: 76 },
        showEffect: false,
        hitFlash: false,
        moveStep: 1,
        effectProgress: 0.48,
        phaseId: "selfdestruct-enemy-walk6",
        phaseName: "#6. 다가가기 (6)",
      },
      // #7. 플레이어 코앞 도착
      {
        ...baseFrame,
        delay: 140,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.52,
        phaseId: "selfdestruct-enemy-reach",
        phaseName: "#7. 코앞 도착",
      },
      // #8. 크리퍼 점멸 틱 1 (1차 팽창 & 순백 플래시)
      {
        ...baseFrame,
        delay: 110,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.03, y: 1.03 },
        casterWhite: true,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.58,
        phaseId: "selfdestruct-enemy-tick1",
        phaseName: "#8. 크리퍼 점멸 1 (순백)",
      },
      // #9. 크리퍼 점멸 틱 1-off (원색 복귀 & 미세 팽창)
      {
        ...baseFrame,
        delay: 110,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.05, y: 1.05 },
        casterWhite: false,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.60,
        phaseId: "selfdestruct-enemy-tick1-off",
        phaseName: "#9. 팽창 대기 1",
      },
      // #10. 크리퍼 점멸 틱 2 (2차 팽창 & 순백 플래시)
      {
        ...baseFrame,
        delay: 100,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.08, y: 1.08 },
        casterWhite: true,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.62,
        phaseId: "selfdestruct-enemy-tick2",
        phaseName: "#10. 크리퍼 점멸 2 (순백)",
      },
      // #11. 크리퍼 점멸 틱 2-off (원색 복귀 & 추가 팽창)
      {
        ...baseFrame,
        delay: 90,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.10, y: 1.10 },
        casterWhite: false,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.64,
        phaseId: "selfdestruct-enemy-tick2-off",
        phaseName: "#11. 팽창 대기 2",
      },
      // #12. 크리퍼 점멸 틱 3 (고속 팽창 & 순백 플래시)
      {
        ...baseFrame,
        delay: 90,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.12, y: 1.12 },
        casterWhite: true,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.66,
        phaseId: "selfdestruct-enemy-tick3",
        phaseName: "#12. 크리퍼 점멸 3 (순백)",
      },
      // #13. 크리퍼 점멸 틱 3-off (원색 복귀 & 임계 직전)
      {
        ...baseFrame,
        delay: 80,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.14, y: 1.14 },
        casterWhite: false,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.68,
        phaseId: "selfdestruct-enemy-tick3-off",
        phaseName: "#13. 팽창 대기 3",
      },
      // #14. 기폭 직전 팽창 (순백 고정 - 크리퍼 기폭 임계!)
      {
        ...baseFrame,
        delay: 140,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        eScale: { x: 1.16, y: 1.16 },
        casterWhite: true,
        showEffect: false,
        hitFlash: false,
        moveStep: 2,
        effectProgress: 0.70,
        phaseId: "selfdestruct-enemy-critical-white",
        phaseName: "#14. 기폭 직전 팽창 (순백 고정)",
      },
      // #15. 펑! 기폭 (상대 산화 소멸 & 백색 섬광 & 최대 셰이크 & 피크 블러)
      {
        ...baseFrame,
        delay: 150,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: 10, y: -7 },
        cameraBlur: 4.5,
        hideEnemy: true,
        enemyHp: 0, // 상대 시전자 즉시 체력 0 기절
        showEffect: true,
        hitFlash: true,
        moveStep: 3,
        effectProgress: 0.72,
        phaseId: "selfdestruct-enemy-detonate",
        phaseName: "#15. 펑! 기폭 (상대 소멸)",
      },
      // #16. 초음속 충격파 분출 (폭풍 반동 셰이크 & 강한 블러)
      {
        ...baseFrame,
        delay: 150,
        pOffset: { x: -22, y: 8 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: -9, y: 7 },
        cameraBlur: 3.8,
        hideEnemy: true,
        enemyHp: 0,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 0.76,
        phaseId: "selfdestruct-enemy-shockwave-burst",
        phaseName: "#16. 충격파 확산 (반동 셰이크 & 블러)",
      },
      // #17. 화구 팽창 & 1차 여진 (강한 셰이크 & 중간 블러 유지)
      {
        ...baseFrame,
        delay: 160,
        pOffset: { x: -38, y: 15 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: 7, y: -5 },
        cameraBlur: 2.8,
        hideEnemy: true,
        enemyHp: 0,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 0.81,
        phaseId: "selfdestruct-enemy-fireball-expand",
        phaseName: "#17. 화구 팽창 (여진 셰이크 & 블러 유지)",
      },
      // #18. 거대 화구 절정 & 플레이어 최대 넉백 (중간 셰이크 & 블러 완화)
      {
        ...baseFrame,
        delay: 180,
        pOffset: { x: -48, y: 20 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: -5, y: 4 },
        cameraBlur: 1.8,
        hideEnemy: true,
        enemyHp: 0,
        playerHp: isHit ? a.playerHpAfter : playerHp,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 0.87,
        phaseId: "selfdestruct-enemy-mushroom-apex",
        phaseName: "#18. 거대 화구 절정 & 최대 넉백",
      },
      // #19. 흑연 연막 확산 & 파편 비산 (소강 셰이크 & 미세 블러)
      {
        ...baseFrame,
        delay: 180,
        pOffset: { x: -30, y: 12 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: 3, y: -2 },
        cameraBlur: 0.8,
        hideEnemy: true,
        enemyHp: 0,
        playerHp: isHit ? a.playerHpAfter : playerHp,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 0.93,
        phaseId: "selfdestruct-enemy-smoke-billow",
        phaseName: "#19. 흑연 연막 확산 (소강 셰이크)",
      },
      // #20. 폭발 잔흔 & 연기 소멸 (미세 잔진 & 선명 복귀)
      {
        ...baseFrame,
        delay: 180,
        pOffset: { x: -14, y: 5 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: -1, y: 1 },
        hideEnemy: true,
        enemyHp: 0,
        playerHp: isHit ? a.playerHpAfter : playerHp,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 0.98,
        phaseId: "selfdestruct-enemy-dissipate",
        phaseName: "#20. 폭발 잔흔 & 연기 소멸",
      },
      // #21. 완전 안정화 & 정렬 (카메라 원위치 복귀)
      {
        ...baseFrame,
        delay: 190,
        pOffset: { x: 0, y: 0 },
        eOffset: { x: -185, y: 86 },
        cameraPan: { x: 0, y: 0 },
        hideEnemy: true,
        enemyHp: 0,
        playerHp: isHit ? a.playerHpAfter : playerHp,
        showEffect: true,
        hitFlash: false,
        moveStep: 3,
        effectProgress: 1.0,
        phaseId: "selfdestruct-enemy-settle",
        phaseName: "#21. 완전 안정화 (원위치 복귀)",
      },
    ];
  },
};
